
export default {
    AUTHENTICATION_REQUEST: "AUTHENTICATION_REQUEST",
    AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
    AUTHENTICATION_FAILURE: "AUTHENTICATION_FAILURE",
    LOGOUT: "LOGOUT"
};
